---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-base

inputs:
- name: cli
outputs:
- name: commit-info

run:
  path: bash
  args:
  - -c
  - |
    set -ex
    git config --get pullrequest.userlogin > commit-info/author-name
    echo "temp - pr builder claim" > commit-info/story
    echo "temp - pr builder claim" > commit-info/author-email
    echo "temp - pr builder claim" > commit-info/committer-name
    echo "temp - pr builder claim" > commit-info/committer-email
    echo "done"
